import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "es" | "en" | "it" | "zh" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navbar
    "nav.home": "Inicio",
    "nav.accommodation": "Alojamiento",
    "nav.things_to_do": "Cosas que hacer",
    "nav.schedule": "Horarios",
    "nav.dress_code": "Etiqueta",
    "nav.mobile_hint": "¡Busca el anillo único y más en los iconos de arriba!",
    
    // Index page
    "index.welcome": "¡Bienvenidos a nuestra boda!",
    "index.date": "14 de Noviembre de 2026",
    "index.location": "Aldea Tejera Negra, Campillo de Ranas, Guadalajara",
    "index.countdown.months": "Meses",
    "index.countdown.days": "Días",
    "index.countdown.hours": "Horas",
    "index.countdown.minutes": "Minutos",
    "index.rsvp.title": "¿Vienes a nuestra boda?",
    "index.rsvp.description": "Por favor, confirma tu asistencia rellenando el siguiente formulario. ¡Nos encantará compartir ese día contigo!",
    "index.venue": "14 de noviembre de 2026\nAldea Tejera Negra.",
    "index.ceremony_time": "Ceremonia a las 13:00h.",
    "index.quote1": "\"Una boda para gobernarlos a todos,",
    "index.quote2": "y en la felicidad atarlos.\"",
    "index.adventure1": "Nos vamos de aventura,",
    "index.adventure2": "¡y te queremos con nosotros!",
    "index.rsvp.button": "Confirmar asistencia",
    "index.rsvp.confirmed": "¡Gracias por confirmar tu asistencia!",
    "index.rsvp.edit": "Editar respuesta",
    
    // Alojamiento page
    "accommodation.title": "Alojamientos en la Zona",
    "accommodation.subtitle": "La finca Tejera Negra nos proporciona el contacto de los siguientes alojamientos/casas rurales por la zona. Por favor escríbenos si tu intención es quedarte a dormir la noche del sábado. ¡Gracias!",
    "accommodation.more.title": "Datos de los alojamientos recomendados",
    "accommodation.table.name": "Nombre",
    "accommodation.table.locality": "Localidad",
    "accommodation.table.phone": "Teléfono",
    "accommodation.table.website": "Página web",
    "accommodation.table.details": "Detalles",
    "accommodation.filter.locality": "Localidad",
    "accommodation.filter.all": "Todos",

    
    // CosasQueHacer page
    "things.title": "Qué Hacer en la Zona",
    "things.subtitle": "Los Pueblos Negros de Guadalajara ofrecen naturaleza, cultura e historia. Aquí tienes algunas sugerencias para disfrutar de tu estancia.",
    "things.villages.title": "Pueblos Recomendados para Visitar",
    "things.tips.title": "💡 Consejos Útiles",
    
    // Activities
    "things.hayedo.title": "Hayedo de Tejera Negra",
    "things.hayedo.description": "Parque Natural declarado Patrimonio de la Humanidad por la UNESCO. Disfruta de sus rutas de senderismo entre hayas centenarias, especialmente espectaculares en otoño.",
    "things.hayedo.distance": "A 5 km",
    "things.pueblos.title": "Pueblos Negros",
    "things.pueblos.description": "Recorre los encantadores pueblos de arquitectura negra: Campillo de Ranas, Majaelrayo, Valverde de los Arroyos, Robleluengo. Casas construidas con pizarra que les dan ese color oscuro característico.",
    "things.pueblos.distance": "En la zona",
    "things.iglesias.title": "Iglesias y Ermitas",
    "things.iglesias.description": "Visita las iglesias románicas y ermitas con encanto de la zona. Destacan la iglesia de Campillo de Ranas y la ermita de la Virgen de la Soledad.",
    "things.iglesias.distance": "En el pueblo",
    "things.senderismo.title": "Rutas de Senderismo",
    "things.senderismo.description": "Múltiples rutas señalizadas por el valle del río Sorbe, cascadas, miradores naturales y paisajes de montaña. Desde rutas sencillas hasta más exigentes.",
    "things.senderismo.distance": "Diversas distancias",
    "things.miradores.title": "Miradores Naturales",
    "things.miradores.description": "Disfruta de impresionantes vistas panorámicas desde los diversos miradores de la zona. Perfectos para fotografía de paisajes y naturaleza.",
    "things.miradores.distance": "Por toda la zona",
    "things.gastronomia.title": "Gastronomía Local",
    "things.gastronomia.description": "Degusta la cocina tradicional serrana: cabrito asado, judías del Barco, trucha del río, setas de temporada y miel de la zona. Varios restaurantes en los pueblos cercanos.",
    "things.gastronomia.distance": "En los pueblos",
    
    // Villages
    "things.village.valverde": "Uno de los pueblos más bonitos de la arquitectura negra",
    "things.village.majaelrayo": "Pueblo con encanto, ideal para pasear por sus calles empedradas",
    "things.village.campillo": "Pueblo base, punto de partida para muchas rutas",
    "things.village.robleluengo": "Pequeño pueblo tranquilo con vistas impresionantes",
    "things.village.tamajon": "Pueblo más grande con servicios y restaurantes",
    
    // Tips
    "things.tip1": "Lleva calzado cómodo para caminar por las calles empedradas y rutas de montaña",
    "things.tip2": "La zona es ideal para desconectar; la cobertura móvil puede ser limitada en algunos puntos",
    "things.tip3": "En otoño (octubre-noviembre) el hayedo está en su máximo esplendor con colores espectaculares",
    "things.tip4": "Reserva con antelación en restaurantes, especialmente los fines de semana",
    
    // Schedule page
    "schedule.title": "Horarios del Evento",
    "schedule.subtitle": "14 de noviembre de 2026 — Así será el día de nuestra boda",
    "schedule.ceremony.title": "Ceremonia",
    "schedule.ceremony.time": "13:00h",
    "schedule.ceremony.description": "Ceremonia nupcial. ¡El momento más especial del día!",
    "schedule.cocktail.title": "Cóctel de Bienvenida",
    "schedule.cocktail.time": "14:00h",
    "schedule.cocktail.description": "Recepción con cóctel de bienvenida para todos los invitados.",
    "schedule.banquet.title": "Banquete",
    "schedule.banquet.time": "15:00h",
    "schedule.banquet.description": "Comienza el banquete nupcial. ¡A disfrutar de la comida!",
    "schedule.openbar.title": "Barra Libre",
    "schedule.openbar.time": "~17:15h (3 horas)",
    "schedule.openbar.description": "Comienza la barra libre con música y fiesta. ¡Durará aproximadamente 3 horas!",
    "schedule.latesupper.title": "Recena",
    "schedule.latesupper.time": "Después de la barra libre",
    "schedule.latesupper.description": "Para reponer fuerzas después de la fiesta, habrá una recena para los que sigan en pie.",
    "schedule.end.title": "Fin de la Fiesta",
    "schedule.end.time": "20:30h",
    "schedule.end.description": "La fiesta terminará como tarde a las 20:30h. ¡Esperamos que hayáis disfrutado tanto como nosotros!",
    
    // Dress Code page
    "dresscode.title": "Etiqueta",
    "dresscode.subtitle": "¡Nuestra boda será una celebración temática inspirada en El Señor de los Anillos y el mundo Hobbit!",
    "dresscode.theme.title": "Boda Temática del Señor de los Anillos",
    "dresscode.theme.description": "Nuestra boda está ambientada en el universo de Tolkien: La Comarca, los Hobbits, la Tierra Media... ¡Queremos que el ambiente sea lo más mágico e inmersivo posible!",
    "dresscode.noobligation.title": "Sin Obligaciones",
    "dresscode.noobligation.description": "Nadie está obligado a disfrazarse ni a vestirse de ninguna manera concreta. Ven como te sientas más cómodo/a. ¡Lo importante es que disfrutes del día! Nadie está obligado tampoco a comprarse nada, si vienes con cualquier cosa que tengas en casa nos parecerá bien!",
    "dresscode.encouraged.title": "¡El Estilo Hobbit Mola!",
    "dresscode.encouraged.description": "Dicho esto... ¡cuanto más te adaptes al estilo Hobbit/Tolkien, mejor! Tirantes, chalecos, faldas largas, tonos tierra, capas, telas naturales... ¡Todo vale para ambientar la fiesta!",
    "dresscode.rule.title": "⚠️ La Única Regla: ¡NO TRAJE NI VESTIDO DE GALA!",
    "dresscode.rule.description": "La única norma que ponemos es que NO se puede venir en traje, ni en vestido de gala (chaqueta y corbata clásicos, o vestido elegante formal). Queremos un ambiente relajado y festivo, ¡no una boda convencional!",
    "dresscode.tips.title": "💡 Ideas e Inspiración",
    "dresscode.tips.tip1": "Tonos tierra, verdes, marrones y ocres son perfectos para el estilo Hobbit",
    "dresscode.tips.tip2": "Tirantes, chalecos, sombreros y accesorios rústicos quedan genial",
    "dresscode.tips.tip3": "Telas naturales como lino, algodón o lana dan un toque muy acertado",
    "dresscode.tips.tip4": "¡Consulta Pinterest buscando 'Hobbit outfit' o 'Lord of the Rings wedding' para inspirarte!",
    "dresscode.buy.title": "Tiendas donde comprar ropa temática",
    
    // Form
    "form.title": "Confirma tu asistencia",
    "form.name": "Nombre completo",
    "form.name.placeholder": "Ej: Ana García",
    "form.plusone": "Llevo acompañante (+1)",
    "form.menu": "Menú preferido",
    "form.color": "Color preferido",
    "form.color.companion": "Color del acompañante",
    "form.song": "¿Qué canción no puede faltar en la fiesta?",
    "form.song.placeholder": "Ej: La Macarena, We Found Love, Toxicity...",
    "form.comments": "Comentarios/adicionales",
    "form.comments.placeholder": "¿Alguna alergia, petición o mensaje para los novios?",
    "form.children": "Vengo con niños",
    "form.children.count": "¿Cuántos niños?",
    "form.children.names": "Nombres y comentarios",
    "form.children.names.placeholder": "Ej: Lucía (3 años), necesita menú sin gluten",
    "form.overnight": "Pernocto el sábado noche",
    "form.consent": "Doy mi consentimiento para aparecer en fotos y vídeos públicos de la boda (en redes, web, etc).",
    "form.submit": "Enviar confirmación",
    "form.error.name": "Por favor, introduce tu nombre.",
    "form.error.companion": "Por favor, introduce el nombre de tu acompañante.",
    "form.error.consent": "Debes aceptar el consentimiento para salir en fotos/vídeos.",
    "form.error.submit": "Ocurrió un error al registrar tu invitación. Por favor intenta de nuevo.",
    "form.error.email": "Por favor, introduce tu correo electrónico.",
    "form.error.duplicate_email": "Ya existe un registro con este correo electrónico. Si quieres hacer algún cambio, por favor háznoslo saber.",
    "form.email": "Correo electrónico",
    "form.email.placeholder": "Ej: ana@email.com",
    "form.expand_to_review": "Pulsa para revisar tus datos",
    "form.success": "¡Registro enviado! Gracias por confirmar tu asistencia.",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.accommodation": "Accommodation",
    "nav.things_to_do": "Things to Do",
    "nav.schedule": "Schedule",
    "nav.dress_code": "Dress Code",
    "nav.mobile_hint": "Find the One Ring & more in the icons above!",
    
    // Index page
    "index.welcome": "Welcome to our wedding!",
    "index.date": "November 14th, 2026",
    "index.location": "Aldea Tejera Negra, Campillo de Ranas, Guadalajara",
    "index.countdown.months": "Months",
    "index.countdown.days": "Days",
    "index.countdown.hours": "Hours",
    "index.countdown.minutes": "Minutes",
    "index.rsvp.title": "Are you coming to our wedding?",
    "index.rsvp.description": "Please confirm your attendance by filling out the form below. We would love to share that day with you!",
    "index.venue": "Nov 14, 2026\nAldea Tejera Negra.",
    "index.ceremony_time": "Ceremony at 1:00 PM.",
    "index.quote1": "\"One wedding to rule them all,",
    "index.quote2": "and in the happiness bind them.\"",
    "index.adventure1": "We're going on an adventure,",
    "index.adventure2": "and we want you with us!",
    "index.rsvp.button": "Confirm attendance",
    "index.rsvp.confirmed": "Thank you for confirming your attendance!",
    "index.rsvp.edit": "Edit response",
    
    // Alojamiento page
    "accommodation.title": "Accommodations in the Area",
    "accommodation.subtitle": "The Tejera Negra estate provides us with the contact details for the following accommodations/rural houses in the area. Please let us know if you plan to stay overnight on Saturday. Thank you!",
    "accommodation.more.title": "Recommended accommodation data",
    "accommodation.table.name": "Name",
    "accommodation.table.locality": "Locality",
    "accommodation.table.phone": "Phone",
    "accommodation.table.website": "Website",
    "accommodation.table.details": "Details",
    "accommodation.filter.locality": "Locality",
    "accommodation.filter.all": "All",
    
    // CosasQueHacer page
    "things.title": "What to Do in the Area",
    "things.subtitle": "The Black Villages of Guadalajara offer nature, culture and history. Here are some suggestions to enjoy your stay.",
    "things.villages.title": "Recommended Villages to Visit",
    "things.tips.title": "💡 Useful Tips",
    
    // Activities
    "things.hayedo.title": "Tejera Negra Beech Forest",
    "things.hayedo.description": "Natural Park declared a UNESCO World Heritage Site. Enjoy its hiking trails among centuries-old beech trees, especially spectacular in autumn.",
    "things.hayedo.distance": "5 km away",
    "things.pueblos.title": "Black Villages",
    "things.pueblos.description": "Explore the charming villages of black architecture: Campillo de Ranas, Majaelrayo, Valverde de los Arroyos, Robleluengo. Houses built with slate that give them their characteristic dark color.",
    "things.pueblos.distance": "In the area",
    "things.iglesias.title": "Churches and Chapels",
    "things.iglesias.description": "Visit the Romanesque churches and charming hermitages in the area. The church of Campillo de Ranas and the hermitage of Virgen de la Soledad stand out.",
    "things.iglesias.distance": "In the village",
    "things.senderismo.title": "Hiking Trails",
    "things.senderismo.description": "Multiple marked trails through the Sorbe river valley, waterfalls, natural viewpoints and mountain landscapes. From easy to challenging routes.",
    "things.senderismo.distance": "Various distances",
    "things.miradores.title": "Natural Viewpoints",
    "things.miradores.description": "Enjoy stunning panoramic views from the various viewpoints in the area. Perfect for landscape and nature photography.",
    "things.miradores.distance": "Throughout the area",
    "things.gastronomia.title": "Local Cuisine",
    "things.gastronomia.description": "Taste traditional mountain cuisine: roasted kid, Barco beans, river trout, seasonal mushrooms and local honey. Several restaurants in nearby villages.",
    "things.gastronomia.distance": "In the villages",
    
    // Villages
    "things.village.valverde": "One of the most beautiful villages of black architecture",
    "things.village.majaelrayo": "Charming village, ideal for strolling through its cobbled streets",
    "things.village.campillo": "Base village, starting point for many routes",
    "things.village.robleluengo": "Small quiet village with impressive views",
    "things.village.tamajon": "Larger village with services and restaurants",
    
    // Tips
    "things.tip1": "Wear comfortable shoes for walking on cobbled streets and mountain trails",
    "things.tip2": "The area is ideal for disconnecting; mobile coverage may be limited in some areas",
    "things.tip3": "In autumn (October-November) the beech forest is at its peak with spectacular colors",
    "things.tip4": "Book restaurants in advance, especially on weekends",
    
    // Schedule page
    "schedule.title": "Event Schedule",
    "schedule.subtitle": "November 14th, 2026 — Here's how our wedding day will unfold",
    "schedule.ceremony.title": "Ceremony",
    "schedule.ceremony.time": "1:00 PM",
    "schedule.ceremony.description": "Wedding ceremony. The most special moment of the day!",
    "schedule.cocktail.title": "Welcome Cocktail",
    "schedule.cocktail.time": "2:00 PM",
    "schedule.cocktail.description": "Welcome cocktail reception for all guests.",
    "schedule.banquet.title": "Banquet",
    "schedule.banquet.time": "3:00 PM",
    "schedule.banquet.description": "The wedding banquet begins. Enjoy the feast!",
    "schedule.openbar.title": "Open Bar",
    "schedule.openbar.time": "~5:15 PM (3 hours)",
    "schedule.openbar.description": "The open bar kicks off with music and partying. It will last approximately 3 hours!",
    "schedule.latesupper.title": "Late Supper",
    "schedule.latesupper.time": "After the open bar",
    "schedule.latesupper.description": "To recharge after the party, there will be a late supper for those still standing.",
    "schedule.end.title": "End of the Party",
    "schedule.end.time": "8:30 PM",
    "schedule.end.description": "The party will end at 8:30 PM at the latest. We hope you enjoyed it as much as we did!",
    
    // Dress Code page
    "dresscode.title": "Dress Code",
    "dresscode.subtitle": "Our wedding will be a Lord of the Rings / Hobbit themed celebration!",
    "dresscode.theme.title": "Lord of the Rings Themed Wedding",
    "dresscode.theme.description": "Our wedding is set in the world of Tolkien: The Shire, the Hobbits, Middle-earth... We want the atmosphere to be as magical and immersive as possible!",
    "dresscode.noobligation.title": "No Obligations",
    "dresscode.noobligation.description": "Nobody is obligated to dress up or wear anything specific. Come however you feel most comfortable. The important thing is that you enjoy the day! Nobody is obligated to buy anything either; if you show up in whatever you already have at home, that’s perfectly fine with us!",
    "dresscode.encouraged.title": "Hobbit Style Is Cool!",
    "dresscode.encouraged.description": "That said... the more you embrace the Hobbit/Tolkien style, the better! Suspenders, waistcoats, long skirts, earth tones, cloaks, natural fabrics... anything goes to set the mood!",
    "dresscode.rule.title": "⚠️ The Only Rule: NO SUITS OR FORMAL DRESSES!",
    "dresscode.rule.description": "The only rule we have is that you CANNOT wear a formal suit or formal dress (classic jacket and tie, or formal elegant dress). We want a relaxed and festive atmosphere — not a conventional wedding!",
    "dresscode.tips.title": "💡 Ideas & Inspiration",
    "dresscode.tips.tip1": "Earth tones, greens, browns and ochres are perfect for the Hobbit style",
    "dresscode.tips.tip2": "Suspenders, waistcoats, hats and rustic accessories look great",
    "dresscode.tips.tip3": "Natural fabrics like linen, cotton or wool add a perfect touch",
    "dresscode.tips.tip4": "Search Pinterest for 'Hobbit outfit' or 'Lord of the Rings wedding' for inspiration!",
    "dresscode.buy.title": "Places to shop for themed attire",
    
    // Form
    "form.title": "Confirm Your Attendance",
    "form.name": "Full Name",
    "form.name.placeholder": "E.g.: Ana García",
    "form.plusone": "Bringing a guest (+1)",
    "form.menu": "Preferred Menu",
    "form.color": "Preferred Color",
    "form.color.companion": "Companion's Color",
    "form.song": "What song can't be missing from the party?",
    "form.song.placeholder": "E.g.: La Macarena, We Found Love, Toxicity...",
    "form.comments": "Comments/Additional Info",
    "form.comments.placeholder": "Any allergies, requests, or message for the bride and groom?",
    "form.children": "I'm coming with children",
    "form.children.count": "How many children?",
    "form.children.names": "Names and comments",
    "form.children.names.placeholder": "E.g.: Lucia (3 years old), needs gluten-free menu",
    "form.overnight": "Staying overnight on Saturday",
    "form.consent": "I consent to appear in public photos and videos of the wedding (on social media, website, etc.).",
    "form.submit": "Send Confirmation",
    "form.error.name": "Please enter your name.",
    "form.error.companion": "Please enter your companion's name.",
    "form.error.consent": "You must accept the consent to appear in photos/videos.",
    "form.error.submit": "An error occurred while registering your invitation. Please try again.",
    "form.error.email": "Please enter your email address.",
    "form.error.duplicate_email": "An account with this email already exists. If you'd like to make changes, please let us know.",
    "form.email": "Email address",
    "form.email.placeholder": "E.g.: ana@email.com",
    "form.expand_to_review": "Click to review your details",
    "form.success": "Registration sent! Thank you for confirming your attendance.",
  },
  it: {
    // Navbar
    "nav.home": "Home",
    "nav.accommodation": "Alloggio",
    "nav.things_to_do": "Cosa Fare",
    "nav.schedule": "Orari",
    "nav.dress_code": "Dress Code",
    "nav.mobile_hint": "Cerca l'Unico Anello e altro nelle icone sopra!",
    
    // Index page
    "index.welcome": "Benvenuti al nostro matrimonio!",
    "index.date": "14 Novembre 2026",
    "index.location": "Aldea Tejera Negra, Campillo de Ranas, Guadalajara",
    "index.countdown.months": "Mesi",
    "index.countdown.days": "Giorni",
    "index.countdown.hours": "Ore",
    "index.countdown.minutes": "Minuti",
    "index.rsvp.title": "Vieni al nostro matrimonio?",
    "index.rsvp.description": "Per favore conferma la tua partecipazione compilando il modulo qui sotto. Ci piacerebbe condividere quel giorno con te!",
    "index.venue": "14 novembre 2026\nAldea Tejera Negra.",
    "index.ceremony_time": "Cerimonia alle 13:00.",
    "index.quote1": "\"Un matrimonio per dominarli tutti,",
    "index.quote2": "e nella felicità legarli.\"",
    "index.adventure1": "Stiamo partendo per un'avventura,",
    "index.adventure2": "e ti vogliamo con noi!",
    "index.rsvp.button": "Conferma partecipazione",
    "index.rsvp.confirmed": "Grazie per aver confermato la tua partecipazione!",
    "index.rsvp.edit": "Modifica risposta",
    
    // Alojamiento page
    "accommodation.title": "Alloggi nella Zona",
    "accommodation.subtitle": "La tenuta Tejera Negra ci fornisce i contatti dei seguenti alloggi/case rurali nella zona. Per favore scrivici se hai intenzione di restare a dormire sabato notte. Grazie!",
    "accommodation.more.title": "Dati degli alloggi consigliati",
    "accommodation.table.name": "Nome",
    "accommodation.table.locality": "Località",
    "accommodation.table.phone": "Telefono",
    "accommodation.table.website": "Sito web",
    "accommodation.table.details": "Dettagli",
    "accommodation.filter.locality": "Località",
    "accommodation.filter.all": "Tutti",
    
    // CosasQueHacer page
    "things.title": "Cosa Fare nella Zona",
    "things.subtitle": "I Villaggi Neri di Guadalajara offrono natura, cultura e storia. Ecco alcuni suggerimenti per goderti il tuo soggiorno.",
    "things.villages.title": "Villaggi Consigliati da Visitare",
    "things.tips.title": "💡 Consigli Utili",
    
    // Activities
    "things.hayedo.title": "Faggeta di Tejera Negra",
    "things.hayedo.description": "Parco Naturale dichiarato Patrimonio dell'Umanità dall'UNESCO. Goditi i suoi sentieri escursionistici tra faggi centenari, particolarmente spettacolari in autunno.",
    "things.hayedo.distance": "A 5 km",
    "things.pueblos.title": "Villaggi Neri",
    "things.pueblos.description": "Esplora gli incantevoli villaggi dell'architettura nera: Campillo de Ranas, Majaelrayo, Valverde de los Arroyos, Robleluengo. Case costruite con ardesia che conferiscono loro il caratteristico colore scuro.",
    "things.pueblos.distance": "Nella zona",
    "things.iglesias.title": "Chiese ed Eremi",
    "things.iglesias.description": "Visita le chiese romaniche e gli affascinanti eremi della zona. Spiccano la chiesa di Campillo de Ranas e l'eremo della Virgen de la Soledad.",
    "things.iglesias.distance": "Nel villaggio",
    "things.senderismo.title": "Sentieri Escursionistici",
    "things.senderismo.description": "Numerosi sentieri segnalati attraverso la valle del fiume Sorbe, cascate, belvedere naturali e paesaggi montani. Da percorsi facili a più impegnativi.",
    "things.senderismo.distance": "Varie distanze",
    "things.miradores.title": "Belvedere Naturali",
    "things.miradores.description": "Goditi splendide viste panoramiche dai vari belvedere della zona. Perfetti per la fotografia di paesaggi e natura.",
    "things.miradores.distance": "In tutta la zona",
    "things.gastronomia.title": "Cucina Locale",
    "things.gastronomia.description": "Assaggia la cucina tradizionale di montagna: capretto arrosto, fagioli del Barco, trota di fiume, funghi di stagione e miele locale. Diversi ristoranti nei villaggi vicini.",
    "things.gastronomia.distance": "Nei villaggi",
    
    // Villages
    "things.village.valverde": "Uno dei villaggi più belli dell'architettura nera",
    "things.village.majaelrayo": "Villaggio affascinante, ideale per passeggiare tra le sue strade acciottolate",
    "things.village.campillo": "Villaggio base, punto di partenza per molti percorsi",
    "things.village.robleluengo": "Piccolo villaggio tranquillo con viste impressionanti",
    "things.village.tamajon": "Villaggio più grande con servizi e ristoranti",
    
    // Tips
    "things.tip1": "Indossa scarpe comode per camminare su strade acciottolate e sentieri di montagna",
    "things.tip2": "La zona è ideale per staccare la spina; la copertura mobile può essere limitata in alcuni punti",
    "things.tip3": "In autunno (ottobre-novembre) la faggeta è al suo massimo splendore con colori spettacolari",
    "things.tip4": "Prenota i ristoranti in anticipo, soprattutto nei fine settimana",
    
    // Schedule page
    "schedule.title": "Programma dell'Evento",
    "schedule.subtitle": "14 novembre 2026 — Ecco come si svolgerà il giorno del nostro matrimonio",
    "schedule.ceremony.title": "Cerimonia",
    "schedule.ceremony.time": "13:00",
    "schedule.ceremony.description": "Cerimonia nuziale. Il momento più speciale della giornata!",
    "schedule.cocktail.title": "Cocktail di Benvenuto",
    "schedule.cocktail.time": "14:00",
    "schedule.cocktail.description": "Ricevimento con cocktail di benvenuto per tutti gli ospiti.",
    "schedule.banquet.title": "Banchetto",
    "schedule.banquet.time": "15:00",
    "schedule.banquet.description": "Inizia il banchetto nuziale. Buon appetito!",
    "schedule.openbar.title": "Open Bar",
    "schedule.openbar.time": "~17:15 (3 ore)",
    "schedule.openbar.description": "Inizia l'open bar con musica e festa. Durerà circa 3 ore!",
    "schedule.latesupper.title": "Cena Tardiva",
    "schedule.latesupper.time": "Dopo l'open bar",
    "schedule.latesupper.description": "Per ricaricare le energie dopo la festa, ci sarà una cena tardiva per chi è ancora in piedi.",
    "schedule.end.title": "Fine della Festa",
    "schedule.end.time": "20:30",
    "schedule.end.description": "La festa terminerà al più tardi alle 20:30. Speriamo che vi siate divertiti quanto noi!",
    
    // Dress Code page
    "dresscode.title": "Dress Code",
    "dresscode.subtitle": "Il nostro matrimonio sarà una celebrazione a tema Il Signore degli Anelli / Hobbit!",
    "dresscode.theme.title": "Matrimonio a Tema Il Signore degli Anelli",
    "dresscode.theme.description": "Il nostro matrimonio è ambientato nel mondo di Tolkien: La Contea, gli Hobbit, la Terra di Mezzo... Vogliamo che l'atmosfera sia il più magica e coinvolgente possibile!",
    "dresscode.noobligation.title": "Nessun Obbligo",
    "dresscode.noobligation.description": "Nessuno è obbligato a travestirsi o a vestirsi in modo particolare. Vieni come ti senti più a tuo agio. L'importante è che ti goda la giornata! Nessuno è obbligato nemmeno a comprarsi nulla; se vieni con qualcosa che hai già in casa, va benissimo per noi!",
    "dresscode.encouraged.title": "Lo Stile Hobbit È Fantastico!",
    "dresscode.encouraged.description": "Detto questo... più ti adatti allo stile Hobbit/Tolkien, meglio è! Bretelle, gilet, gonne lunghe, tonalità terra, mantelli, tessuti naturali... tutto va bene per creare l'atmosfera!",
    "dresscode.rule.title": "⚠️ L'Unica Regola: NIENTE ABITI FORMALI NE VESTITI ELEGANTI!",
    "dresscode.rule.description": "L'unica regola che mettiamo è che NON si può venire in abito formale o vestito elegante (giacca e cravatta classici, o vestito elegante formale). Vogliamo un'atmosfera rilassata e festosa — non un matrimonio convenzionale!",
    "dresscode.tips.title": "💡 Idee e Ispirazione",
    "dresscode.tips.tip1": "Tonalità terra, verdi, marroni e ocra sono perfetti per lo stile Hobbit",
    "dresscode.tips.tip2": "Bretelle, gilet, cappelli e accessori rustici stanno benissimo",
    "dresscode.tips.tip3": "Tessuti naturali come lino, cotone o lana danno un tocco perfetto",
    "dresscode.tips.tip4": "Cerca su Pinterest 'Hobbit outfit' o 'Lord of the Rings wedding' per ispirarti!",
    "dresscode.buy.title": "Negozi dove acquistare abiti a tema",
    
    // Form
    "form.title": "Conferma la Tua Partecipazione",
    "form.name": "Nome Completo",
    "form.name.placeholder": "Es: Ana García",
    "form.plusone": "Porto un accompagnatore (+1)",
    "form.menu": "Menu Preferito",
    "form.color": "Colore Preferito",
    "form.color.companion": "Colore dell'Accompagnatore",
    "form.song": "Quale canzone non può mancare alla festa?",
    "form.song.placeholder": "Es: La Macarena, We Found Love, Toxicity...",
    "form.comments": "Commenti/Informazioni Aggiuntive",
    "form.comments.placeholder": "Allergie, richieste o messaggi per gli sposi?",
    "form.children": "Vengo con bambini",
    "form.children.count": "Quanti bambini?",
    "form.children.names": "Nomi e commenti",
    "form.children.names.placeholder": "Es: Lucia (3 anni), necessita menu senza glutine",
    "form.overnight": "Pernotto sabato notte",
    "form.consent": "Acconsento ad apparire in foto e video pubblici del matrimonio (sui social, sito web, ecc.).",
    "form.submit": "Invia Conferma",
    "form.error.name": "Inserisci il tuo nome.",
    "form.error.companion": "Inserisci il nome del tuo accompagnatore.",
    "form.error.consent": "Devi accettare il consenso per apparire in foto/video.",
    "form.error.submit": "Si è verificato un errore durante la registrazione dell'invito. Riprova.",
    "form.success": "Registrazione inviata! Grazie per aver confermato la tua partecipazione.",
  },
  zh: {
    // Navbar
    "nav.home": "首页",
    "nav.accommodation": "住宿",
    "nav.things_to_do": "周边活动",
    "nav.schedule": "时间表",
    "nav.dress_code": "着装要求",
    "nav.mobile_hint": "在上方图标中寻找至尊魔戒和更多内容！",
    
    // Index page
    "index.welcome": "欢迎参加我们的婚礼！",
    "index.date": "2026年11月14日",
    "index.location": "Aldea Tejera Negra, Campillo de Ranas, Guadalajara",
    "index.countdown.months": "月",
    "index.countdown.days": "天",
    "index.countdown.hours": "小时",
    "index.countdown.minutes": "分钟",
    "index.rsvp.title": "你会来参加我们的婚礼吗？",
    "index.rsvp.description": "请填写下面的表格确认您的出席。我们很期待与您共度这一天！",
    "index.venue": "2026年11月14日\nAldea Tejera Negra。",
    "index.ceremony_time": "仪式于13:00开始。",
    "index.quote1": "\"一场婚礼统领所有，",
    "index.quote2": "在幸福中将他们联结。\"",
    "index.adventure1": "我们即将踏上冒险之旅，",
    "index.adventure2": "希望有你同行！",
    "index.rsvp.button": "确认出席",
    "index.rsvp.confirmed": "感谢您确认出席！",
    "index.rsvp.edit": "修改回复",
    
    // Alojamiento page
    "accommodation.title": "附近住宿",
    "accommodation.subtitle": "Tejera Negra庄园为我们提供了以下地区住宿/乡村民宿的联系方式。如果您打算周六晚上留宿，请联系我们。谢谢！",
    "accommodation.more.title": "推荐住宿资料",
    "accommodation.table.name": "名称",
    "accommodation.table.locality": "位置",
    "accommodation.table.phone": "电话",
    "accommodation.table.website": "网站",
    "accommodation.table.details": "详细信息",
    "accommodation.filter.locality": "位置",
    "accommodation.filter.all": "全部",
    
    // CosasQueHacer page
    "things.title": "周边活动",
    "things.subtitle": "瓜达拉哈拉的黑村提供自然、文化和历史体验。以下是一些享受您住宿的建议。",
    "things.villages.title": "推荐参观的村庄",
    "things.tips.title": "💡 实用建议",
    
    // Activities
    "things.hayedo.title": "Tejera Negra 山毛榉林",
    "things.hayedo.description": "被联合国教科文组织列为世界遗产的自然公园。在百年山毛榉间享受徒步旅行，秋季尤为壮观。",
    "things.hayedo.distance": "5公里",
    "things.pueblos.title": "黑村",
    "things.pueblos.description": "探索迷人的黑色建筑村庄：Campillo de Ranas、Majaelrayo、Valverde de los Arroyos、Robleluengo。用板岩建造的房屋赋予它们独特的深色外观。",
    "things.pueblos.distance": "在该地区",
    "things.iglesias.title": "教堂和礼拜堂",
    "things.iglesias.description": "参观该地区的罗马式教堂和迷人的小教堂。Campillo de Ranas教堂和Virgen de la Soledad小教堂尤为突出。",
    "things.iglesias.distance": "在村庄内",
    "things.senderismo.title": "徒步路线",
    "things.senderismo.description": "Sorbe河谷、瀑布、自然观景台和山地景观中有多条标记路线。从简单到具有挑战性的路线都有。",
    "things.senderismo.distance": "各种距离",
    "things.miradores.title": "自然观景台",
    "things.miradores.description": "从该地区各个观景台欣赏令人惊叹的全景。非常适合风景和自然摄影。",
    "things.miradores.distance": "遍布全区",
    "things.gastronomia.title": "当地美食",
    "things.gastronomia.description": "品尝传统山区美食：烤山羊肉、Barco豆、河鳟鱼、时令蘑菇和当地蜂蜜。附近村庄有多家餐厅。",
    "things.gastronomia.distance": "在各村庄",
    
    // Villages
    "things.village.valverde": "最美丽的黑色建筑村庄之一",
    "things.village.majaelrayo": "迷人的村庄，非常适合在鹅卵石街道漫步",
    "things.village.campillo": "基地村庄，许多路线的起点",
    "things.village.robleluengo": "安静的小村庄，景色令人印象深刻",
    "things.village.tamajon": "较大的村庄，有服务设施和餐厅",
    
    // Tips
    "things.tip1": "穿舒适的鞋子，方便在鹅卵石街道和山间小道行走",
    "things.tip2": "该地区非常适合放松身心；某些地区的手机信号可能有限",
    "things.tip3": "秋季（10月-11月）山毛榉林色彩最为壮观",
    "things.tip4": "提前预订餐厅，尤其是周末",
    
    // Schedule page
    "schedule.title": "活动时间表",
    "schedule.subtitle": "2026年11月14日——我们婚礼当天的安排",
    "schedule.ceremony.title": "婚礼仪式",
    "schedule.ceremony.time": "13:00",
    "schedule.ceremony.description": "婚礼仪式。一天中最特别的时刻！",
    "schedule.cocktail.title": "欢迎鸡尾酒会",
    "schedule.cocktail.time": "14:00",
    "schedule.cocktail.description": "为所有宾客举办的欢迎鸡尾酒会。",
    "schedule.banquet.title": "宴会",
    "schedule.banquet.time": "15:00",
    "schedule.banquet.description": "婚宴开始，尽情享用美食！",
    "schedule.openbar.title": "畅饮时间",
    "schedule.openbar.time": "约17:15（3小时）",
    "schedule.openbar.description": "畅饮时间开始，伴随音乐和派对。将持续约3小时！",
    "schedule.latesupper.title": "夜宵",
    "schedule.latesupper.time": "畅饮时间之后",
    "schedule.latesupper.description": "派对结束后，为仍在场的宾客提供夜宵补充体力。",
    "schedule.end.title": "派对结束",
    "schedule.end.time": "20:30",
    "schedule.end.description": "派对最迟将在20:30结束。希望您和我们一样尽兴！",
    
    // Dress Code page
    "dresscode.title": "着装要求",
    "dresscode.subtitle": "我们的婚礼将是一场《指环王》/霍比特人主题的庆祝活动！",
    "dresscode.theme.title": "指环王主题婚礼",
    "dresscode.theme.description": "我们的婚礼以托尔金的世界为背景：夏尔、霍比特人、中土世界……我们希望氛围尽可能充满魔法和沉浸感！",
    "dresscode.noobligation.title": "没有强制要求",
    "dresscode.noobligation.description": "没有人被要求必须装扮成特定样子。穿你觉得最舒服的衣服来就好。最重要的是你能享受这一天！也没有人被要求去买任何东西；如果你穿家里已有的任何东西来，我们会觉得很好的！",
    "dresscode.encouraged.title": "霍比特风格超酷！",
    "dresscode.encouraged.description": "话虽如此……你越贴近霍比特人/托尔金的风格越好！背带裤、马甲、长裙、大地色系、斗篷、天然面料……一切都能帮助营造氛围！",
    "dresscode.rule.title": "⚠️ 唯一的规则：不能穿西装或正式礼服！",
    "dresscode.rule.description": "我们唯一的规则是不能穿正式西装或正式礼服（经典的西装外套和领带，或正式优雅连衣裙）。我们希望营造轻松愉快的氛围——而不是传统婚礼！",
    "dresscode.tips.title": "💡 灵感与建议",
    "dresscode.tips.tip1": "大地色系、绿色、棕色和赭色非常适合霍比特风格",
    "dresscode.tips.tip2": "背带裤、马甲、帽子和乡村风配饰效果很好",
    "dresscode.tips.tip3": "亚麻、棉花或羊毛等天然面料增添完美质感",
    "dresscode.tips.tip4": "在Pinterest上搜索'Hobbit outfit'或'Lord of the Rings wedding'获取灵感！",
    "dresscode.buy.title": "购买主题服装的商店",
    
    // Form
    "form.title": "确认您的出席",
    "form.name": "全名",
    "form.name.placeholder": "例如：Ana García",
    "form.plusone": "我带同伴 (+1)",
    "form.menu": "首选菜单",
    "form.color": "首选颜色",
    "form.color.companion": "同伴的颜色",
    "form.song": "派对上不能缺少什么歌曲？",
    "form.song.placeholder": "例如：La Macarena, We Found Love, Toxicity...",
    "form.comments": "评论/附加信息",
    "form.comments.placeholder": "有过敏、要求或给新人的留言吗？",
    "form.children": "我带孩子来",
    "form.children.count": "几个孩子？",
    "form.children.names": "姓名和备注",
    "form.children.names.placeholder": "例如：Lucia（3岁），需要无麸质菜单",
    "form.overnight": "周六晚上留宿",
    "form.consent": "我同意出现在婚礼的公开照片和视频中（社交媒体、网站等）。",
    "form.submit": "发送确认",
    "form.error.name": "请输入您的姓名。",
    "form.error.companion": "请输入您同伴的姓名。",
    "form.error.consent": "您必须接受出现在照片/视频中的同意声明。",
    "form.error.submit": "注册邀请时发生错误。请重试。",
    "form.success": "注册已发送！感谢您确认出席。",
  },
  de: {
    // Navbar
    "nav.home": "Startseite",
    "nav.accommodation": "Unterkunft",
    "nav.things_to_do": "Aktivitäten",
    "nav.schedule": "Zeitplan",
    "nav.dress_code": "Dresscode",
    "nav.mobile_hint": "Finde den Einen Ring & mehr in den Icons oben!",
    
    // Index page
    "index.welcome": "Willkommen zu unserer Hochzeit!",
    "index.date": "14. November 2026",
    "index.location": "Aldea Tejera Negra, Campillo de Ranas, Guadalajara",
    "index.countdown.months": "Monate",
    "index.countdown.days": "Tage",
    "index.countdown.hours": "Stunden",
    "index.countdown.minutes": "Minuten",
    "index.rsvp.title": "Kommst du zu unserer Hochzeit?",
    "index.rsvp.description": "Bitte bestätige deine Teilnahme, indem du das folgende Formular ausfüllst. Wir würden diesen Tag gerne mit dir teilen!",
    "index.venue": "14. November 2026\nAldea Tejera Negra.",
    "index.ceremony_time": "Zeremonie um 13:00 Uhr.",
    "index.quote1": "\"Eine Hochzeit, sie zu knechten,",
    "index.quote2": "sie alle ins Glück zu binden.\"",
    "index.adventure1": "Wir gehen auf ein Abenteuer,",
    "index.adventure2": "und wir wollen dich dabei haben!",
    "index.rsvp.button": "Teilnahme bestätigen",
    "index.rsvp.confirmed": "Danke für deine Bestätigung!",
    "index.rsvp.edit": "Antwort bearbeiten",
    
    // Alojamiento page
    "accommodation.title": "Unterkünfte in der Umgebung",
    "accommodation.subtitle": "Das Anwesen Tejera Negra stellt uns die Kontaktdaten folgender Unterkünfte/Landhäuser in der Umgebung zur Verfügung. Bitte teile uns mit, ob du am Samstagabend übernachten möchtest. Danke!",
    "accommodation.more.title": "Empfohlene Unterkunftsdaten",
    "accommodation.table.name": "Name",
    "accommodation.table.locality": "Ort",
    "accommodation.table.phone": "Telefon",
    "accommodation.table.website": "Webseite",
    "accommodation.table.details": "Details",
    "accommodation.filter.locality": "Ort",
    "accommodation.filter.all": "Alle",
    
    // CosasQueHacer page
    "things.title": "Aktivitäten in der Umgebung",
    "things.subtitle": "Die Schwarzen Dörfer von Guadalajara bieten Natur, Kultur und Geschichte. Hier sind einige Vorschläge, um deinen Aufenthalt zu genießen.",
    "things.villages.title": "Empfohlene Dörfer zum Besuchen",
    "things.tips.title": "💡 Nützliche Tipps",
    
    // Activities
    "things.hayedo.title": "Buchenwald von Tejera Negra",
    "things.hayedo.description": "Naturpark, der zum UNESCO-Weltkulturerbe erklärt wurde. Genieße die Wanderwege zwischen jahrhundertealten Buchen, besonders spektakulär im Herbst.",
    "things.hayedo.distance": "5 km entfernt",
    "things.pueblos.title": "Schwarze Dörfer",
    "things.pueblos.description": "Erkunde die charmanten Dörfer der schwarzen Architektur: Campillo de Ranas, Majaelrayo, Valverde de los Arroyos, Robleluengo. Häuser aus Schiefer, die ihnen ihre charakteristische dunkle Farbe verleihen.",
    "things.pueblos.distance": "In der Umgebung",
    "things.iglesias.title": "Kirchen und Kapellen",
    "things.iglesias.description": "Besuche die romanischen Kirchen und charmanten Einsiedeleien der Umgebung. Besonders sehenswert sind die Kirche von Campillo de Ranas und die Einsiedelei der Virgen de la Soledad.",
    "things.iglesias.distance": "Im Dorf",
    "things.senderismo.title": "Wanderwege",
    "things.senderismo.description": "Zahlreiche markierte Wege durch das Sorbe-Flusstal, Wasserfälle, natürliche Aussichtspunkte und Berglandschaften. Von einfachen bis anspruchsvollen Routen.",
    "things.senderismo.distance": "Verschiedene Entfernungen",
    "things.miradores.title": "Natürliche Aussichtspunkte",
    "things.miradores.description": "Genieße atemberaubende Panoramablicke von den verschiedenen Aussichtspunkten der Umgebung. Perfekt für Landschafts- und Naturfotografie.",
    "things.miradores.distance": "In der gesamten Umgebung",
    "things.gastronomia.title": "Lokale Küche",
    "things.gastronomia.description": "Probiere die traditionelle Bergküche: gebratenes Zicklein, Barco-Bohnen, Flussforelle, saisonale Pilze und lokalen Honig. Mehrere Restaurants in den umliegenden Dörfern.",
    "things.gastronomia.distance": "In den Dörfern",
    
    // Villages
    "things.village.valverde": "Eines der schönsten Dörfer der schwarzen Architektur",
    "things.village.majaelrayo": "Charmantes Dorf, ideal zum Spazierengehen durch seine Kopfsteinpflasterstraßen",
    "things.village.campillo": "Basisdorf, Ausgangspunkt für viele Routen",
    "things.village.robleluengo": "Kleines ruhiges Dorf mit beeindruckender Aussicht",
    "things.village.tamajon": "Größeres Dorf mit Dienstleistungen und Restaurants",
    
    // Tips
    "things.tip1": "Trage bequeme Schuhe zum Gehen auf Kopfsteinpflasterstraßen und Bergwegen",
    "things.tip2": "Die Gegend ist ideal zum Abschalten; der Mobilfunkempfang kann in einigen Bereichen eingeschränkt sein",
    "things.tip3": "Im Herbst (Oktober-November) ist der Buchenwald in seiner vollen Pracht mit spektakulären Farben",
    "things.tip4": "Reserviere Restaurants im Voraus, besonders an Wochenenden",
    
    // Schedule page
    "schedule.title": "Veranstaltungszeitplan",
    "schedule.subtitle": "14. November 2026 — So wird unser Hochzeitstag ablaufen",
    "schedule.ceremony.title": "Zeremonie",
    "schedule.ceremony.time": "13:00 Uhr",
    "schedule.ceremony.description": "Hochzeitszeremonie. Der besonderste Moment des Tages!",
    "schedule.cocktail.title": "Willkommenscocktail",
    "schedule.cocktail.time": "14:00 Uhr",
    "schedule.cocktail.description": "Willkommenscocktail-Empfang für alle Gäste.",
    "schedule.banquet.title": "Bankett",
    "schedule.banquet.time": "15:00 Uhr",
    "schedule.banquet.description": "Das Hochzeitsbankett beginnt. Guten Appetit!",
    "schedule.openbar.title": "Offene Bar",
    "schedule.openbar.time": "~17:15 Uhr (3 Stunden)",
    "schedule.openbar.description": "Die offene Bar startet mit Musik und Party. Sie dauert ungefähr 3 Stunden!",
    "schedule.latesupper.title": "Spätabendessen",
    "schedule.latesupper.time": "Nach der offenen Bar",
    "schedule.latesupper.description": "Um nach der Party neue Energie zu tanken, gibt es ein Spätabendessen für diejenigen, die noch stehen.",
    "schedule.end.title": "Ende der Feier",
    "schedule.end.time": "20:30 Uhr",
    "schedule.end.description": "Die Feier endet spätestens um 20:30 Uhr. Wir hoffen, ihr hattet genauso viel Spaß wie wir!",
    
    // Dress Code page
    "dresscode.title": "Dresscode",
    "dresscode.subtitle": "Unsere Hochzeit wird eine Feier im Stil von Der Herr der Ringe / Hobbit!",
    "dresscode.theme.title": "Herr der Ringe Themenhochzeit",
    "dresscode.theme.description": "Unsere Hochzeit spielt in Tolkiens Welt: Das Auenland, die Hobbits, Mittelerde... Wir möchten, dass die Atmosphäre so magisch und immersiv wie möglich ist!",
    "dresscode.noobligation.title": "Keine Verpflichtungen",
    "dresscode.noobligation.description": "Niemand ist verpflichtet, sich zu verkleiden oder etwas Bestimmtes zu tragen. Komm so, wie du dich am wohlsten fühlst. Das Wichtigste ist, dass du den Tag genießt! Niemand ist außerdem verpflichtet, etwas zu kaufen; wenn du in irgendetwas kommst, das du bereits zu Hause hast, ist das für uns völlig in Ordnung!",
    "dresscode.encouraged.title": "Hobbit-Stil ist cool!",
    "dresscode.encouraged.description": "Allerdings... je mehr du dich dem Hobbit/Tolkien-Stil anpasst, desto besser! Hosenträger, Westen, lange Röcke, Erdtöne, Umhänge, natürliche Stoffe... alles ist erlaubt, um die Stimmung zu setzen!",
    "dresscode.rule.title": "⚠️ Die einzige Regel: KEINE ANZÜGE UND KEINE FORMALEN KLEIDER!",
    "dresscode.rule.description": "Die einzige Regel ist, dass man KEINEN formellen Anzug oder formales Kleid (klassische Jacke und Krawatte oder formales elegantes Kleid) tragen darf. Wir wollen eine entspannte und festliche Atmosphäre — keine konventionelle Hochzeit!",
    "dresscode.tips.title": "💡 Ideen & Inspiration",
    "dresscode.tips.tip1": "Erdtöne, Grün, Braun und Ocker sind perfekt für den Hobbit-Stil",
    "dresscode.tips.tip2": "Hosenträger, Westen, Hüte und rustikale Accessoires sehen großartig aus",
    "dresscode.tips.tip3": "Natürliche Stoffe wie Leinen, Baumwolle oder Wolle geben den perfekten Touch",
    "dresscode.tips.tip4": "Suche auf Pinterest nach 'Hobbit outfit' oder 'Lord of the Rings wedding' für Inspiration!",
    "dresscode.buy.title": "Geschäfte für thematische Kleidung",
    
    // Form
    "form.title": "Bestätige deine Teilnahme",
    "form.name": "Vollständiger Name",
    "form.name.placeholder": "Z.B.: Ana García",
    "form.plusone": "Bringe eine Begleitung mit (+1)",
    "form.menu": "Bevorzugtes Menü",
    "form.color": "Bevorzugte Farbe",
    "form.color.companion": "Farbe der Begleitung",
    "form.song": "Welches Lied darf auf der Party nicht fehlen?",
    "form.song.placeholder": "Z.B.: La Macarena, We Found Love, Toxicity...",
    "form.comments": "Kommentare/Zusätzliches",
    "form.comments.placeholder": "Allergien, Wünsche oder eine Nachricht an das Brautpaar?",
    "form.children": "Ich komme mit Kindern",
    "form.children.count": "Wie viele Kinder?",
    "form.children.names": "Namen und Kommentare",
    "form.children.names.placeholder": "Z.B.: Lucia (3 Jahre), braucht glutenfreies Menü",
    "form.overnight": "Übernachte am Samstagabend",
    "form.consent": "Ich stimme zu, in öffentlichen Fotos und Videos der Hochzeit zu erscheinen (in sozialen Medien, auf der Website usw.).",
    "form.submit": "Bestätigung senden",
    "form.error.name": "Bitte gib deinen Namen ein.",
    "form.error.companion": "Bitte gib den Namen deiner Begleitung ein.",
    "form.error.consent": "Du musst der Zustimmung zustimmen, in Fotos/Videos zu erscheinen.",
    "form.error.submit": "Beim Registrieren deiner Einladung ist ein Fehler aufgetreten. Bitte versuche es erneut.",
    "form.success": "Registrierung gesendet! Danke für die Bestätigung deiner Teilnahme.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
