// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvmxvdhecutldevmmjbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2bXh2ZGhlY3V0bGRldm1tamJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjM4OTIsImV4cCI6MjA2NTQ5OTg5Mn0.JiEyveR9o2oRU1ySXW6V598TDC81vW9JuU7xi3wQjRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);